import AppProvider from '@/components/provider/AppProvider';
import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
  title: "Product Kami - Company Profile CMS",
  description: "Generated by create next app",
};

const layout = ({children}:{children:React.ReactNode}) => {
  return (
    <AppProvider>
      {children}
    </AppProvider>
  );
}

export default layout